<?php
    $feed = $this->getFeed();
    $utils = $this->getUtils();

    // TODO: Empty list
?>
<h1>Новости</h1>
<section class="full-news">
    <?php foreach($feed as $entry): ?>
        <?php if($entry->isPublished()): ?>
            <article class="news-entry">
                <header>
                    <h2><a href="<?php echo $utils->makeUrl($entry->getUrl()); ?>"><?= $entry->getTitle(); ?></a></h2>
                    <em><?php echo $utils->prettyDate(new DateTime($entry->getTimestampCreated())); ?></em>
                </header>
                <section class="news-entry-content">
                    <?php echo $utils->truncateWords($entry->getArticle(), 60); ?>
                </section>
                <footer>
                    <!-- TODO: check for existing url -->
                    <a href="<?php echo $utils->makeUrl($entry->getUrl()); ?>">Read more</a>
                </footer>
            </article>
        <?php endif; ?>
    <?php endforeach; ?>
    <?php echo $this->getPager(); ?>
</section>