<?php
    $feed = $this->getLast();
    $utils = $this->getUtils();
?>
<h5>Got news?</h5>
<section class="yanws side-news">
    <?php foreach($feed as $entry): ?>
        <article class="news-entry">
            <header>
                <?php echo Mage::helper('core/url'); ?>
                <h2><a href="<?php echo $utils->makeUrl($entry->getUrl()); ?>"><?= $entry->getTitle(); ?></a></h2>
                <em><?php echo $utils->prettyDate(new DateTime($entry->getTimestampCreated())); ?></em>
            </header>
            <section class="yanws news-entry-content">
                <?php echo $utils->truncateWords($entry->getArticle(), 15); ?>
            </section>
            <footer>
                <!-- TODO: check for existing url -->
                <a href="<?php echo $utils->makeUrl($entry->getUrl()); ?>">Read more</a>
            </footer>
        </article>
    <?php endforeach; ?>
    <footer class="yanws news-link">
        <a href="<?php echo $utils->getUrl(); ?>" >More news</a>
    </footer>
</section>