<?php
    $entry = $this->getEntry();
    $links = $this->getLinks();
    $utils = $this->getUtils();
?>

<section class="yanws-entry-view">
    <article class="news-entry">
        <header>
            <h2><?= $entry->getTitle()?></h2>
            <em><?= $utils->prettyDate(new DateTime($entry->getTimestampCreated())); ?></em>
        </header>
        <section class="news-entry-content">
            <?= $entry->getArticle(); ?>
        </section>
        <footer>
            <a href="<?php echo $utils->makeUrl($links["prev"]->getUrl()) ?>"><?php echo $links["prev"]->getTitle() ?></a>
            <a href="<?php echo $utils->makeUrl($links["next"]->getUrl()) ?>"><?php echo $links["next"]->getTitle() ?></a>
        </footer>
    </article>
</section>
