<?php
    $newsId = Mage::app()->getRequest()->getParam('id', 0);
    $article = Mage::getModel('yanws/news')->load($newsId);

    if (!($article->getId() > 0)) {
        $this->_forward('noRoute');
    } ?>

<article class="news-entry full">
    <header>
        <h2><?= $article['title']?></h2>
        <em><?= Mage::helper('yanws/prettyDateTime')->parse(new DateTime($article['timestamp_created'])); ?></em>
    </header>
    <section class="news-entry-content">
        <?= $article['article']; ?>
    </section>
    <footer>

    </footer>
</article>