<?php
    $title = $this->getTitle();
    $feed = $this->getLast();
    $utils = $this->getUtils();
?>
<h5><?php echo $title; ?></h5>
<section class="yanws side-news">
    <?php foreach($feed as $entry): ?>
        <article class="news-entry">
            <header>
                <em><?php echo $utils->prettyDate(new DateTime($entry->getTimestampCreated())); ?></em>
                <h4><a href="<?php echo $utils->makeUrl($entry->getUrl()); ?>"><?= $entry->getTitle(); ?></a></h4>
            </header>
            <section class="yanws news-entry-content">
                <?php echo $utils->truncateWords($entry->getArticle(), 15); ?>
            </section>
            <footer>
                <!-- TODO: check for existing url -->
                <a href="<?php echo $utils->makeUrl($entry->getUrl()); ?>"><?php echo $this->__('Read more'); ?></a>
            </footer>
        </article>
    <?php endforeach; ?>
    <footer class="yanws news-link">
        <a href="<?php echo $utils->getUrl(); ?>" ><?php echo $this->__('More news'); ?></a>
    </footer>
</section>