<?php
    $title = $this->getTitle();
    $feed = $this->getLast();
    $utils = $this->getUtils();
?>
<div class="block-title"><strong><span><?php echo $title; ?></span></strong></div>
<section class="yanws side-news">
    <?php foreach($feed as $entry): ?>
        <article class="news-entry">
            <header>
                <em><?php echo $utils->prettyDate(new DateTime($entry->getTimestampCreated())); ?></em>
                <h4><a href="<?php echo $utils->makeViewUrl($entry->getUrl()); ?>"><?= $entry->getTitle(); ?></a></h4>
            </header>
            <section class="yanws news-entry-content">
                <?php echo $this->getShorten($entry); ?>
            </section>
            <footer>
                <a href="<?php echo $utils->makeViewUrl($entry->getUrl()); ?>"><?php echo $this->__('Read more'); ?></a>
            </footer>
        </article>
    <?php endforeach; ?>
    <footer class="yanws news-link">
        <a href="<?php echo $utils->getUrl(); ?>" ><?php echo $this->__('More news'); ?></a>
    </footer>
</section>